#!/usr/bin/env bash

for battery in /sys/class/power_supply/BAT?*; do
    [ -n "${capacity+x}" ] && printf " "
    capacity="$(cat "$battery/capacity" 2>&1)"

    case "$(cat "$battery/status" 2>&1)" in
        "Full") status="🔋 " ;;
        "Discharging") status="🪫 " ;;
        "Charging") status="🌀 " ;;
        "Not charging") status="🔋 " ;;
        "Unknown") status="❓ " ;;
        *) exit 1 ;;
    esac
    
    if [ "$capacity" -ge 50 ]; then
        status="🔋 "
    fi
    [ "$status" = "🪫 " ] && [ "$capacity" -le 25 ] && status="❗ "
    
    printf "%s%s%d%%" "$warn" "$status" "$capacity"; unset warn
done && printf "\\n"
