#!/usr/bin/env bash

volume=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -oP '\d+%' | head -1)
mute=$(pactl get-sink-mute @DEFAULT_SINK@ | grep -oP '(?<=Mute: ).*')

if [ "$mute" = "yes" ]; then
    echo "🔇 $volume"
else
    echo "🔊 $volume"
fi
