[general]
import = [
    "~/.config/alacritty/colors.toml",
    "~/.config/alacritty/font.toml"
]

[window]
padding = { y = 5, x = 10 }
dynamic_padding = true

[cursor]
style.shape = "Beam"
style.blinking = "on"
blink_interval = 700

[keyboard]
bindings = [
  { key = "K", mods = "Alt", action = "ScrollHalfPageUp" },
  { key = "J", mods = "Alt", action = "ScrollHalfPageDown" },
]
